version: "3.8"

services:
  db:
    container_name: manifest_db
    image: postgres:15.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: manifest
      POSTGRES_PASSWORD: postgres